# Generated by Django 5.1.3 on 2024-11-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baggage",
            options={},
        ),
        migrations.RemoveField(
            model_name="baggage",
            name="flight",
        ),
        migrations.AddField(
            model_name="baggage",
            name="reservation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baggages",
                to="flight.reservation",
            ),
            preserve_default=False,
        ),
    ]
